export const INDUSTRIES = [
  "Accounting",
  "Legal",
  "Consulting",
  "Engineering",
  "Architecture",
  "IT Services",
  "Marketing",
  "Other",
];

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Argentina", "Australia", "Austria",
  "Bangladesh", "Belgium", "Bolivia", "Botswana", "Brazil", "Canada",
  "Chile", "China", "Colombia", "Costa Rica", "Croatia", "Czech Republic",
  "Denmark", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Estonia", "Ethiopia", "Finland", "France", "Germany", "Ghana", "Greece",
  "Guatemala", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
  "Indonesia", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan",
  "Kenya", "Latvia", "Lebanon", "Lithuania", "Luxembourg", "Malaysia",
  "Mauritius", "Mexico", "Morocco", "Mozambique", "Namibia", "Netherlands",
  "New Zealand", "Nigeria", "Norway", "Pakistan", "Panama", "Paraguay",
  "Peru", "Philippines", "Poland", "Portugal", "Romania", "Rwanda",
  "Saudi Arabia", "Senegal", "Singapore", "Slovakia", "Slovenia",
  "South Africa", "South Korea", "Spain", "Sri Lanka", "Sweden",
  "Switzerland", "Taiwan", "Tanzania", "Thailand", "Trinidad and Tobago",
  "Tunisia", "Turkey", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Venezuela", "Vietnam",
  "Zambia", "Zimbabwe",
];
